//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string productCode { get; set; }
        public string productName { get; set; }
        public string productLine { get; set; }
        public string productScale { get; set; }
        public string productVendor { get; set; }
        public string productDescription { get; set; }
        public short quantityInStock { get; set; }
        public decimal buyPrice { get; set; }
        public decimal MSRP { get; set; }
    }
}
