//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDisplay.ProductReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="product", Namespace="http://schemas.datacontract.org/2004/07/ProductServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MSRPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal buyPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productScaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productVendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short quantityInStockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MSRP {
            get {
                return this.MSRPField;
            }
            set {
                if ((this.MSRPField.Equals(value) != true)) {
                    this.MSRPField = value;
                    this.RaisePropertyChanged("MSRP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal buyPrice {
            get {
                return this.buyPriceField;
            }
            set {
                if ((this.buyPriceField.Equals(value) != true)) {
                    this.buyPriceField = value;
                    this.RaisePropertyChanged("buyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.productCodeField, value) != true)) {
                    this.productCodeField = value;
                    this.RaisePropertyChanged("productCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.productDescriptionField, value) != true)) {
                    this.productDescriptionField = value;
                    this.RaisePropertyChanged("productDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productLine {
            get {
                return this.productLineField;
            }
            set {
                if ((object.ReferenceEquals(this.productLineField, value) != true)) {
                    this.productLineField = value;
                    this.RaisePropertyChanged("productLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                if ((object.ReferenceEquals(this.productNameField, value) != true)) {
                    this.productNameField = value;
                    this.RaisePropertyChanged("productName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productScale {
            get {
                return this.productScaleField;
            }
            set {
                if ((object.ReferenceEquals(this.productScaleField, value) != true)) {
                    this.productScaleField = value;
                    this.RaisePropertyChanged("productScale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productVendor {
            get {
                return this.productVendorField;
            }
            set {
                if ((object.ReferenceEquals(this.productVendorField, value) != true)) {
                    this.productVendorField = value;
                    this.RaisePropertyChanged("productVendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short quantityInStock {
            get {
                return this.quantityInStockField;
            }
            set {
                if ((this.quantityInStockField.Equals(value) != true)) {
                    this.quantityInStockField = value;
                    this.RaisePropertyChanged("quantityInStock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductReference.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/productList", ReplyAction="http://tempuri.org/IProductService/productListResponse")]
        System.Collections.Generic.List<ProductDisplay.ProductReference.product> productList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/productList", ReplyAction="http://tempuri.org/IProductService/productListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProductDisplay.ProductReference.product>> productListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/sortList", ReplyAction="http://tempuri.org/IProductService/sortListResponse")]
        System.Collections.Generic.List<ProductDisplay.ProductReference.product> sortList(string choice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/sortList", ReplyAction="http://tempuri.org/IProductService/sortListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProductDisplay.ProductReference.product>> sortListAsync(string choice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/displayStat", ReplyAction="http://tempuri.org/IProductService/displayStatResponse")]
        string displayStat(string choice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/displayStat", ReplyAction="http://tempuri.org/IProductService/displayStatResponse")]
        System.Threading.Tasks.Task<string> displayStatAsync(string choice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : ProductDisplay.ProductReference.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<ProductDisplay.ProductReference.IProductService>, ProductDisplay.ProductReference.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ProductDisplay.ProductReference.product> productList() {
            return base.Channel.productList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProductDisplay.ProductReference.product>> productListAsync() {
            return base.Channel.productListAsync();
        }
        
        public System.Collections.Generic.List<ProductDisplay.ProductReference.product> sortList(string choice) {
            return base.Channel.sortList(choice);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProductDisplay.ProductReference.product>> sortListAsync(string choice) {
            return base.Channel.sortListAsync(choice);
        }
        
        public string displayStat(string choice) {
            return base.Channel.displayStat(choice);
        }
        
        public System.Threading.Tasks.Task<string> displayStatAsync(string choice) {
            return base.Channel.displayStatAsync(choice);
        }
    }
}
